# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            
tagline:          A log of things that I figured out once.
url:              http://peachjean.github.io
paginate:         1
baseurl:          /
author:
  name:           Jared Bunting
  url:            https://github.com/peachjean
  email:          jared.bunting@peachjean.com

